adorsys/open-banking-gateway

- README.md
- docs/ContributionGuidelines.md
Just  documentation for the ContributionGuildlines.
> OBG-#23 Contribution Guilelines added

- .travis.yml
add the openshift target env vars globally
> add global env to travis.yml

- scripts/deploy_openshift.sh
docker login without oc
commented oc for testing
> reset openshift deployment strategy to default

- opba-banking-rest-api/pom.xml
Removed swagger generated tests (they are useless) and imporved generated source detection by IntelliJ
> Removed generated tests

- .travis.yml
- core/banking-protocol/pom.xml
- core/pom.xml
- last-module-codecoverage/pom.xml
- opba-banking-rest-api/pom.xml
- opba-consent-rest-api/pom.xml
- opba-consent-rest-api/src/main/java/de/adorsys/opba/consent/rest/api/resource/ConsentAuthorisationApi.java
- opba-embedded-starter/pom.xml
- pom.xml
- sandbox-test/e2e-tests/pom.xml
- sandbox-test/pom.xml
> Fix deploy to mvn central

- .gitignore
- .travis.yml
- Makefile
- README.md
- docs/ContributionGuidelines.md
- docs/getting_started.md
> Restructure README.md, add getting started guide

- fintech-examples/fintech-api/pom.xml
- fintech-examples/fintech-api/src/main/resources/static/fintech_api.yml
Generated code didn't run without this changes
> fintech api fix

- README.md
- docs/ContributionGuidelines.md
- docs/getting_started.md
- last-module-codecoverage/pom.xml
- lombok.config
- pom.xml
- scripts/build_mvn.sh
Successor of 
https://github.com/adorsys/open-banking-gateway/pull/186
Added build and codecov badge
> JaCoCo re-enabled

- core/banking-protocol/src/main/java/de/adorsys/opba/core/protocol/constant/GlobalConst.java
- fintech-examples/fintech-api/pom.xml
- fintech-examples/fintech-api/src/main/java/de/adorsys/opba/fintech/api/resource/AccountInformationResource.java
- fintech-examples/fintech-api/src/main/java/de/adorsys/opba/fintech/api/resource/AuthorizationResource.java
- fintech-examples/fintech-api/src/main/java/de/adorsys/opba/fintech/api/resource/BankSearchResource.java
- fintech-examples/fintech-impl/pom.xml
- fintech-examples/fintech-impl/src/main/java/de/adorsys/opba/fintech/impl/config/FinTechImplConfig.java
- fintech-examples/fintech-impl/src/main/java/de/adorsys/opba/fintech/impl/controller/FinTechAuthorizationImpl.java
- fintech-examples/fintech-impl/src/main/java/de/adorsys/opba/fintech/impl/controller/FinTechBankSearchImpl.java
- fintech-examples/fintech-impl/src/main/java/de/adorsys/opba/fintech/impl/service/AuthorizeService.java
- fintech-examples/fintech-impl/src/main/java/de/adorsys/opba/fintech/impl/service/BankSearchService.java
- fintech-examples/fintech-impl/src/main/java/de/adorsys/opba/fintech/impl/service/mapper/Mapper.java
- fintech-examples/fintech-server/src/test/java/de/adorsys/opba/fintech/server/FinTechServerTests.java
- last-module-codecoverage/pom.xml
- opba-banking-rest-api/pom.xml
- opba-banking-rest-api/src/main/java/de/adorsys/opba/tppbankingapi/ais/resource/AccountListMapper.java
- opba-banking-rest-api/src/main/java/de/adorsys/opba/tppbankingapi/ais/resource/TppBankingApiAisResource.java
- opba-banking-rest-api/src/main/java/de/adorsys/opba/tppbankingapi/token/TppBankingApiTokenResource.java
- opba-banking-rest-api/src/test/java/de/adorsys/opba/tppbankingapi/ais/resource/AccountListMapperTest.java
- opba-banking-rest-impl/src/main/java/de/adorsys/opba/tppbankingapi/controller/TppBankSearchController.java
- opba-banking-rest-impl/src/main/java/de/adorsys/opba/tppbankingapi/domain/entity/Bank.java
- opba-banking-rest-impl/src/main/java/de/adorsys/opba/tppbankingapi/domain/entity/BankProfile.java
- opba-banking-rest-impl/src/test/java/de/adorsys/opba/tppbankingapi/domain/MappersTest.java
- opba-consent-rest-api/pom.xml
- opba-consent-rest-api/src/main/java/de/adorsys/opba/consentapi/resource/ConsentServiceResource.java
Also JaCoCo excludes gen. code now
> OBG-195. Special packages for generated code

- fintech-examples/fintech-ui/package-lock.json
- fintech-examples/fintech-ui/package.json
- fintech-examples/fintech-ui/proxy.conf.json
- fintech-examples/fintech-ui/src/app/app-routing.module.ts
- fintech-examples/fintech-ui/src/app/app.module.ts
- fintech-examples/fintech-ui/src/app/bank-search/common/profile/profile.component.html
- fintech-examples/fintech-ui/src/app/bank-search/common/profile/profile.component.spec.ts
- fintech-examples/fintech-ui/src/app/bank-search/common/profile/profile.component.ts
- fintech-examples/fintech-ui/src/app/bank-search/components/bank-search/bank-search.component.html
- fintech-examples/fintech-ui/src/app/bank-search/components/bank-search/bank-search.component.spec.ts
- fintech-examples/fintech-ui/src/app/bank-search/components/bank-search/bank-search.component.ts
- fintech-examples/fintech-ui/src/app/bank-search/models/bank-profile.model.ts
- fintech-examples/fintech-ui/src/app/bank-search/models/bank.model.ts
- fintech-examples/fintech-ui/src/app/bank-search/services/bank-profile.service.spec.ts
- fintech-examples/fintech-ui/src/app/bank-search/services/bank-profile.service.ts
- fintech-examples/fintech-ui/src/app/bank-search/services/bank-search.service.spec.ts
- fintech-examples/fintech-ui/src/app/bank-search/services/bank-search.service.ts
- fintech-examples/fintech-ui/src/app/common/sidebar/sidebar.component.spec.ts
- fintech-examples/fintech-ui/src/app/dashboard/dashboard.component.spec.ts
- fintech-examples/fintech-ui/src/app/dashboard/home/home.component.spec.ts
- fintech-examples/fintech-ui/src/app/guards/auth.guard.spec.ts
- fintech-examples/fintech-ui/src/app/guards/guest.guard.ts
- fintech-examples/fintech-ui/src/app/interceptors/auth.interceptor.ts
- fintech-examples/fintech-ui/src/app/login/login.component.spec.ts
- fintech-examples/fintech-ui/src/app/login/login.component.ts
- fintech-examples/fintech-ui/src/app/services/auth.service.spec.ts
- fintech-examples/fintech-ui/src/app/services/auth.service.ts
- fintech-examples/fintech-ui/src/environments/environment.prod.ts
- fintech-examples/fintech-ui/src/environments/environment.ts
New UI with working version on cookie service and xsrf-token header
> Bind fintech UI with fintech server using csrf token and cookie

- fintech-examples/fintech-ui/src/app/dashboard/home/home.component.html
- fintech-examples/fintech-ui/src/app/dashboard/home/home.component.ts
- fintech-examples/fintech-ui/src/app/dashboard/services/ais.service.ts
Really first step for implementing account data
> fintech-ui: connect current ui with account list backend endpoints

- fintech-examples/fintech-ui/src/app/app-routing.module.ts
- fintech-examples/fintech-ui/src/app/common/redirect-page/redirect-page.component.html
- fintech-examples/fintech-ui/src/app/common/redirect-page/redirect-page.component.spec.ts
- fintech-examples/fintech-ui/src/app/common/redirect-page/redirect-page.component.ts
- fintech-examples/fintech-ui/src/app/common/share.module.ts
redirect to aspsp page in fintech-ui
> add redirect-page component, redirect back to search on cancel

- README.md
- opba-protocols/xs2a-protocol/src/main/java/de/adorsys/opba/protocol/xs2a/service/xs2a/dto/consent/ConsentInitiateBody.java
- pom.xml
- technical-embedded-ui/tpp-ui/src/app/account-selector/account-selector.component.ts
> OBG-275. Fixed all accounts with balances issue

- technical-embedded-ui/tpp-ui/src/app/account-reference-selector/account-reference.component.html
- technical-embedded-ui/tpp-ui/src/app/account-reference-selector/account-reference.component.ts
- technical-embedded-ui/tpp-ui/src/app/account-selector/account-selector.component.html
- technical-embedded-ui/tpp-ui/src/app/account-selector/account-selector.component.ts
- technical-embedded-ui/tpp-ui/src/app/app-ais-consent/app-ais-consent.component.html
- technical-embedded-ui/tpp-ui/src/app/app-ais-consent/app-ais-consent.component.spec.ts
- technical-embedded-ui/tpp-ui/src/app/app-ais-consent/app-ais-consent.component.ts
- technical-embedded-ui/tpp-ui/src/app/app.module.ts
- technical-embedded-ui/tpp-ui/src/app/dynamic-form/dynamic-form-control-base.ts
- technical-embedded-ui/tpp-ui/src/app/dynamic-form/dynamic-form-control.component.html
- technical-embedded-ui/tpp-ui/src/app/dynamic-form/dynamic-form-control.component.ts
- technical-embedded-ui/tpp-ui/src/app/dynamic-form/dynamic-form.component.html
- technical-embedded-ui/tpp-ui/src/app/dynamic-form/dynamic-form.component.ts
- technical-embedded-ui/tpp-ui/src/app/globals.ts
- technical-embedded-ui/tpp-ui/src/app/parameters-input/parameters-input.component.html
- technical-embedded-ui/tpp-ui/src/app/parameters-input/parameters-input.component.ts
- technical-embedded-ui/tpp-ui/src/app/three-state-checkbox/three-state-checkbox.component.ts
> OBG-270. Frontend (technical UI) changes

- fintech-examples/fintech-server/src/main/resources/application.yml
Please be careful with changing server ports.
It breaks our environments and the dockerfiles also:
server:
port: 18086
> fix fintech-server port

- technical-embedded-ui/tpp-ui/package.json
- technical-embedded-ui/tpp-ui/proxy-conf-dev-backend-dev-consent-ui.js
Allow technical UI to drive DEV
> Helper profiles to use all remote servers

- consent-ui/.prettierignore
- consent-ui/.prettierrc
- consent-ui/angular.json
- consent-ui/package-lock.json
- consent-ui/package.json
- consent-ui/tslint.json
> configure code formatter

- consent-ui/package-lock.json
- consent-ui/src/app/ais/ais-routing.module.ts
- consent-ui/src/app/ais/ais.module.ts
- consent-ui/src/app/ais/common/consent-util.ts
- consent-ui/src/app/ais/common/dto/auth-state.ts
- consent-ui/src/app/ais/common/stub-util.ts
- consent-ui/src/app/ais/components/consent-info/consent-info.component.ts
- consent-ui/src/app/ais/entry-page/initiation/accounts/accounts-consent-review/accounts-consent-review.component.ts
- consent-ui/src/app/ais/entry-page/initiation/accounts/entry-page-accounts/entry-page-accounts.component.ts
- consent-ui/src/app/ais/entry-page/initiation/common/accounts-reference/accounts-reference.component.ts
- consent-ui/src/app/ais/entry-page/initiation/common/dedicated-access/dedicated-access.component.ts
- consent-ui/src/app/ais/entry-page/initiation/common/dynamic-inputs/dynamic-inputs.component.ts
- consent-ui/src/app/ais/entry-page/initiation/common/initial-consent/consent-account-access-selection.component.ts
- consent-ui/src/app/ais/entry-page/initiation/common/shared-routes.ts
- consent-ui/src/app/ais/entry-page/initiation/consent-initiate/consent-initiate.component.ts
- consent-ui/src/app/ais/entry-page/initiation/transactions/entry-page-transactions/entry-page-transactions.component.ts
- consent-ui/src/app/ais/entry-page/initiation/transactions/transactions-consent-review/transactions-consent-review.component.ts
- consent-ui/src/app/ais/password-input-page/password-input-page.component.ts
- consent-ui/src/app/ais/result-page/result-page.component.ts
- consent-ui/src/app/ais/sca-select-page/sca-select-page.component.ts
- consent-ui/src/app/ais/to-aspsp-page/to-aspsp-redirection.component.ts
- consent-ui/src/app/app.module.ts
- consent-ui/src/app/services/consent-auth.service.ts
- consent-ui/tslint.json
- opba-embedded-starter/src/main/resources/application.yml
1) use redirectCode from sessionStorage
2) make lint happy
> use redirectCode from sessionStorage

- .travis.yml
- opba-consent-rest-api/src/main/resources/static/tpp_consent_api.yml
- opba-embedded-starter/pom.xml
- opba-embedded-starter/src/main/resources/application.yml
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-sandbox/src/main/java/de/adorsys/opba/protocol/xs2a/tests/e2e/sandbox/servers/SandboxServers.java
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-sandbox/src/main/java/de/adorsys/opba/protocol/xs2a/tests/e2e/sandbox/servers/WebDriverBasedAccountInformation.java
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-sandbox/src/main/java/de/adorsys/opba/protocol/xs2a/tests/e2e/sandbox/servers/config/RetryableConfig.java
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/java/de/adorsys/opba/protocol/xs2a/tests/Const.java
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/java/de/adorsys/opba/protocol/xs2a/tests/TestProfiles.java
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/java/de/adorsys/opba/protocol/xs2a/tests/e2e/stages/AccountInformationRequestCommon.java
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/java/de/adorsys/opba/protocol/xs2a/tests/e2e/stages/AccountInformationResult.java
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/java/de/adorsys/opba/protocol/xs2a/tests/e2e/stages/CommonGivenStages.java
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/resources/application-test-one-time-postgres-ramfs.yml
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/resources/restrecord/tpp-ui-input/params/anton-brueckner-transactions-single-account-consent.json
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/resources/restrecord/tpp-ui-input/params/max-musterman-transactions-single-account-consent.json
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-wiremock/src/test/java/de/adorsys/opba/protocol/xs2a/tests/e2e/wiremock/WiremockE2EXs2aProtocolTest.java
- opba-protocols/xs2a-protocol-tests/xs2a-stress-test/src/test/java/de/adorsys/opba/protocol/xs2a/tests/e2e/wiremock/stress/WiremockE2EStressXs2aProtocolTest.java
- pom.xml
- scripts/validate_dev_deploy.sh
- smoke-tests/pom.xml
- smoke-tests/src/test/java/de/adorsys/opba/smoketests/SmokeE2ETest.java
- smoke-tests/src/test/java/smoketests/SmokeE2ETest.java
- smoke-tests/src/test/resources/application-test-smoke.yml
Smoke tests for OPBA development deployment (API only)
Fixes #408
> Smoke tests for OPBA API

- .travis.yml
- Makefile
- consent-ui/karma.conf.js
- consent-ui/src/app/ais/common/services/customize.service.spec.ts
- consent-ui/src/app/ais/common/stub-util-tests.ts
- consent-ui/src/app/ais/components/consent-info/consent-info.component.spec.ts
- consent-ui/src/app/ais/entry-page/entry-page.component.spec.ts
- consent-ui/src/app/ais/entry-page/initiation/accounts/accounts-consent-review/accounts-consent-review.component.spec.ts
- consent-ui/src/app/ais/entry-page/initiation/accounts/entry-page-accounts/entry-page-accounts.component.spec.ts
- consent-ui/src/app/ais/entry-page/initiation/common/accounts-reference/accounts-reference.component.spec.ts
- consent-ui/src/app/ais/entry-page/initiation/common/dedicated-access/dedicated-access.component.spec.ts
- consent-ui/src/app/ais/entry-page/initiation/common/dynamic-inputs/dynamic-inputs.component.spec.ts
- consent-ui/src/app/ais/entry-page/initiation/common/initial-consent/consent-account-access-selection.component.spec.ts
- consent-ui/src/app/ais/entry-page/initiation/consent-initiate/consent-initiate.component.spec.ts
- consent-ui/src/app/ais/entry-page/initiation/transactions/entry-page-transactions/entry-page-transactions.component.spec.ts
- consent-ui/src/app/ais/entry-page/initiation/transactions/transactions-consent-review/transactions-consent-review.component.spec.ts
- consent-ui/src/app/ais/error-page/error-page.component.spec.ts
- consent-ui/src/app/ais/password-input-page/password-input-page.component.spec.ts
- consent-ui/src/app/ais/result-page/result-page.component.spec.ts
- consent-ui/src/app/ais/route-based-card-with-sidebar/route-based-card-with-sidebar.component.spec.ts
- consent-ui/src/app/ais/sca-result-page/sca-result-page.component.spec.ts
- consent-ui/src/app/ais/sca-select-page/sca-select-page.component.spec.ts
- consent-ui/src/app/ais/sidebar/sidebar.component.spec.ts
- consent-ui/src/app/ais/to-aspsp-page/to-aspsp-redirection.component.spec.ts
- consent-ui/src/app/app.component.spec.ts
- consent-ui/src/app/services/consent-auth.service.spec.ts
- fixed tests
- ng test to travis ci
> Obg 421/feature ng tests consent ui

- Makefile
codecov script in Travis uploads our generated files automatically so no need to push them manually after code coverage generation
> add code coverage to make file

- consent-ui/src/app/ais/password-input-page/password-input-page.component.html
- consent-ui/src/app/ais/password-input-page/password-input-page.component.spec.ts
- consent-ui/src/app/ais/password-input-page/password-input-page.component.ts
- consent-ui/src/app/ais/sca-result-page/sca-result-page.component.html
- consent-ui/src/app/ais/sca-result-page/sca-result-page.component.spec.ts
- consent-ui/src/app/ais/sca-result-page/sca-result-page.component.ts
- opba-banking-protocol-facade/src/test/resources/application-test.yml
- opba-embedded-starter/src/main/resources/application.yml
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/java/de/adorsys/opba/protocol/xs2a/tests/e2e/stages/AccountInformationRequestCommon.java
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/resources/application-test-one-time-postgres-ramfs.yml
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/resources/restrecord/tpp-ui-input/params/max-musterman-wrong-password.json
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/resources/restrecord/tpp-ui-input/params/max-musterman-wrong-sca-challenge-result.json
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-wiremock/src/main/resources/mockedsandbox/restrecord/embedded/multi-sca/accounts/sandbox/__files/body-v1-consents-456567.json
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-wiremock/src/main/resources/mockedsandbox/restrecord/embedded/multi-sca/accounts/sandbox/mappings/mapping-v1-consents-15252.json
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-wiremock/src/main/resources/mockedsandbox/restrecord/embedded/multi-sca/accounts/sandbox/mappings/mapping-v1-consents-456567.json
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-wiremock/src/main/resources/mockedsandbox/restrecord/embedded/multi-sca/transactions/sandbox/__files/body-v1-consents-356567.json
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-wiremock/src/main/resources/mockedsandbox/restrecord/embedded/multi-sca/transactions/sandbox/mappings/mapping-v1-consents-150625.json
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-wiremock/src/main/resources/mockedsandbox/restrecord/embedded/multi-sca/transactions/sandbox/mappings/mapping-v1-consents-356567.json
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-wiremock/src/test/java/de/adorsys/opba/protocol/xs2a/tests/e2e/wiremock/WiremockE2EXs2aProtocolTest.java
- opba-protocols/xs2a-protocol/src/main/java/de/adorsys/opba/protocol/xs2a/config/aspspmessages/AspspMessages.java
- opba-protocols/xs2a-protocol/src/main/java/de/adorsys/opba/protocol/xs2a/service/xs2a/consent/Xs2aConsentInfo.java
- opba-protocols/xs2a-protocol/src/main/java/de/adorsys/opba/protocol/xs2a/service/xs2a/consent/authenticate/embedded/AuthorizationErrorSink.java
- opba-protocols/xs2a-protocol/src/main/java/de/adorsys/opba/protocol/xs2a/service/xs2a/consent/authenticate/embedded/Xs2aAuthenticateUserConsent.java
- opba-protocols/xs2a-protocol/src/main/java/de/adorsys/opba/protocol/xs2a/service/xs2a/consent/authenticate/embedded/Xs2aReportScaChallenge.java
- opba-protocols/xs2a-protocol/src/main/java/de/adorsys/opba/protocol/xs2a/service/xs2a/context/BaseContext.java
- opba-protocols/xs2a-protocol/src/main/resources/application.yml
- opba-protocols/xs2a-protocol/src/main/resources/processes/xs2a/consent/xs2a-authorize-consent.bpmn20.xml
Fixes #501 
But need to have fix from sandbox as well
> Add support for user password input retry

- docker-compose.yml
- fintech-examples/fintech-ui/package.json
- fintech-examples/fintech-ui/src/app/app-routing.module.ts
- fintech-examples/fintech-ui/src/app/app.module.ts
- fintech-examples/fintech-ui/src/app/redirect-after-consent-denied/redirect-after-consent-denied.component.html
- fintech-examples/fintech-ui/src/app/redirect-after-consent-denied/redirect-after-consent-denied.component.spec.ts
- fintech-examples/fintech-ui/src/app/redirect-after-consent-denied/redirect-after-consent-denied.component.ts
> Obg 497 consent denied page

- fintech-examples/fintech-ui/package.json
- fintech-examples/fintech-ui/src/app/app-routing.module.ts
- fintech-examples/fintech-ui/src/app/bank/list-accounts/list-accounts-routing.module.ts
- fintech-examples/fintech-ui/src/app/bank/list-accounts/list-accounts.component.ts
- fintech-examples/fintech-ui/src/app/bank/list-accounts/list.accounts.component.spec.ts
- fintech-examples/fintech-ui/src/app/bank/list-transactions/list-transactions.component.ts
- fintech-examples/fintech-ui/src/app/bank/list-transactions/list.transactions.component.spec.ts
- fintech-examples/fintech-ui/src/app/bank/sidebar/sidebar.component.ts
- fintech-examples/fintech-ui/src/app/services/auth.service.spec.ts
> Obg 540/fix routing

- fintech-examples/fintech-ui/src/app/bank/redirect-page/redirect-page.component.html
- fintech-examples/fintech-ui/src/app/bank/redirect-page/redirect-page.component.scss
- fintech-examples/fintech-ui/src/app/redirect-after-consent-denied/redirect-after-consent-denied.component.spec.ts
- fintech-examples/fintech-ui/src/app/redirect-after-consent-denied/redirect-after-consent-denied.component.ts
make redirection-card as modal
> #508 dialog should be higher

- fintech-examples/fintech-ui/src/app/login/login.component.html
- fintech-examples/fintech-ui/src/app/login/login.component.ts
> Obg 492/bugfix fintech login validators

- fintech-examples/fintech-ui/src/app/bank/list-transactions/list-transactions.component.html
display remittance information in transaction list
> display remittance information in transaction list

- docker-compose.yml
- fintech-examples/fintech-impl/src/test/resources/application.yml
- fintech-examples/fintech-server/src/main/resources/application.yml
- fintech-examples/fintech-server/src/test/resources/application.yml
New variable in docker-compose, that's why Tarkan is reviewer for that part.
> obg-484 Simplify FinTech routing

- fintech-examples/fintech-ui/package-lock.json
- fintech-examples/fintech-ui/package.json
- fintech-examples/fintech-ui/src/app/app.component.ts
- fintech-examples/fintech-ui/src/app/common/share.module.ts
Using external NgbModalModule from ng-bootstrap and setting global config for it
> Obg 603 modal window component

- consent-ui/src/app/errorsHandler/global-errors-handler.ts
> OBG-654: fix issue with global error handler catching error only once

- fintech-examples/fintech-impl/src/main/java/de/adorsys/opba/fintech/impl/config/FeignConfig.java
- fintech-examples/fintech-impl/src/main/java/de/adorsys/opba/fintech/impl/tppclients/HeaderFields.java
- fintech-examples/fintech-impl/src/main/java/de/adorsys/opba/fintech/impl/tppclients/QueryFields.java
- opba-api-security/pom.xml
- opba-api-security/src/main/java/de/adorsys/opba/api/security/external/domain/FilterValidationHeaderValues.java
- opba-api-security/src/main/java/de/adorsys/opba/api/security/external/domain/HttpHeaders.java
- opba-api-security/src/main/java/de/adorsys/opba/api/security/external/domain/OperationType.java
- opba-api-security/src/main/java/de/adorsys/opba/api/security/external/domain/QueryParams.java
- opba-api-security/src/main/java/de/adorsys/opba/api/security/external/domain/signdata/AisListAccountsDataToSign.java
- opba-api-security/src/main/java/de/adorsys/opba/api/security/external/domain/signdata/AisListTransactionsDataToSign.java
- opba-api-security/src/main/java/de/adorsys/opba/api/security/external/domain/signdata/BankProfileDataToSign.java
- opba-api-security/src/main/java/de/adorsys/opba/api/security/external/domain/signdata/BankSearchDataToSign.java
- opba-api-security/src/main/java/de/adorsys/opba/api/security/external/domain/signdata/ConfirmConsentDataToSign.java
- opba-api-security/src/main/java/de/adorsys/opba/api/security/external/mapper/FeignTemplateToDataToSignMapper.java
- opba-api-security/src/main/java/de/adorsys/opba/api/security/external/mapper/HttpRequestToDataToSignMapper.java
- opba-api-security/src/main/java/de/adorsys/opba/api/security/external/service/RequestSigningService.java
- opba-api-security/src/main/java/de/adorsys/opba/api/security/external/service/RsaJwtsSigningServiceImpl.java
- opba-api-security/src/main/java/de/adorsys/opba/api/security/internal/filter/RequestSignatureValidationFilter.java
- opba-api-security/src/main/java/de/adorsys/opba/api/security/internal/service/RequestVerifyingService.java
- opba-api-security/src/main/java/de/adorsys/opba/api/security/internal/service/RsaJwtsVerifyingServiceImpl.java
- opba-banking-rest-impl/src/main/java/de/adorsys/opba/tppbankingapi/config/RequestVerifyingConfig.java
- opba-banking-rest-impl/src/test/java/de/adorsys/opba/tppbankingapi/controller/TestBankSearchPerformance.java
- opba-banking-rest-impl/src/test/java/de/adorsys/opba/tppbankingapi/controller/TestTppBankSearchController.java
- opba-embedded-starter-tests/src/test/java/de/adorsys/opba/starter/BasicOpenBankingStartupTest.java
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/java/de/adorsys/opba/protocol/xs2a/tests/GetTransactionsQueryParams.java
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/java/de/adorsys/opba/protocol/xs2a/tests/e2e/stages/AccountInformationRequestCommon.java
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/java/de/adorsys/opba/protocol/xs2a/tests/e2e/stages/AccountInformationResult.java
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/java/de/adorsys/opba/protocol/xs2a/tests/e2e/stages/AisStagesCommonUtil.java
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-wiremock/src/main/java/de/adorsys/opba/protocol/xs2a/tests/e2e/wiremock/mocks/WiremockAccountInformationRequest.java
The implementation of the fifth subtask of https://github.com/adorsys/open-banking-gateway/issues/493
> OBG-493: init commit, required fields are signed by fintech

- fintech-examples/fintech-impl/src/main/java/de/adorsys/opba/fintech/impl/config/FeignConfig.java
- opba-api-security/src/main/java/de/adorsys/opba/api/security/external/mapper/FeignTemplateToDataToSignMapper.java
Signature error (due to url encoding) fixed
Missing header field date in Response fixed
> Develop branch signature filter fix

- opba-protocols/sandboxes/xs2a-sandbox/pom.xml
- pom.xml
- smoke-tests/pom.xml
testcontainers released fix for quay issue
https://github.com/testcontainers/testcontainers-java/releases/tag/1.14.3
> update testcontainers to 1.14.3 (fixed issue with quay.io)

- fintech-examples/fintech-ui/src/app/login/login.component.spec.ts
- fintech-examples/fintech-ui/src/app/services/auth.service.spec.ts
> Obg 502/bugfix fix fintechui login tests

- consent-ui/src/app/ais/enter-pin-page/enter-pin-page.component.spec.ts
> Obg 675/bugfix auth service on submit

- fintech-examples/fintech-ui/src/app/bank/list-accounts/list-accounts.component.html
- fintech-examples/fintech-ui/src/app/bank/list-accounts/list-accounts.component.ts
- opba-db/src/main/resources/migration/migrations/0002-mock-data.xml
- opba-protocols/hbci-protocol/src/main/java/de/adorsys/opba/protocol/hbci/entrypoint/HbciResultBodyExtractor.java
- opba-protocols/hbci-protocol/src/main/java/de/adorsys/opba/protocol/hbci/service/consent/HbciConsentInfo.java
- opba-protocols/hbci-protocol/src/main/java/de/adorsys/opba/protocol/hbci/service/consent/authentication/HbciAskForTan.java
- opba-protocols/hbci-protocol/src/main/java/de/adorsys/opba/protocol/hbci/service/consent/authentication/HbciInitiateSendPinAndPsuId.java
- opba-protocols/hbci-protocol/src/main/java/de/adorsys/opba/protocol/hbci/service/consent/authentication/HbciSubmitSelectedMethodAndAskForTanChallenge.java
- opba-protocols/hbci-protocol/src/main/java/de/adorsys/opba/protocol/hbci/service/protocol/ais/HbciAccountListing.java
- opba-protocols/hbci-protocol/src/main/resources/processes/hbci/accounts/hbci-list-accounts.bpmn20.xml
- opba-protocols/hbci-protocol/src/main/resources/processes/hbci/accounts/hbci-list-transactions.bpmn20.xml
- Using BBAN when IBAN not available
- Restructured SCA challenges
> Using BBAN when account number is not available (HBCI)

- fintech-examples/fintech-ui/src/app/bank/bank.component.ts
- fintech-examples/fintech-ui/src/app/bank/list-accounts/list-accounts.component.ts
- fintech-examples/fintech-ui/src/app/bank/payment/payment-initiate/initiate.component.ts
- fintech-examples/fintech-ui/src/app/bank/redirect-page/redirect-page.component.ts
- fintech-examples/fintech-ui/src/app/bank/services/consent-authorization.service.ts
- fintech-examples/fintech-ui/src/app/services/storage.service.ts
Please note that this is a hot fix Pull request, since Fintech UI simply redirects to the URL from Fintech Server.
This is an alternative approach to handle redirection with local storage before issue will be resolved or Fintech Ui refactored
The issue on the Fintech Server side is addressed [here](https://github.com/adorsys/open-banking-gateway/issues/848)
> Obg 802/bugfix with local storage

- fintech-examples/fintech-ui/src/app/bank/sidebar/sidebar.component.html
- fintech-examples/fintech-ui/src/app/bank/sidebar/sidebar.component.ts
apply disabled class to nav-link if service is disabled
> disable payment navlink when payment bot possible

- fintech-examples/fintech-example-tests/src/test/java/de/adorsys/fintech/tests/e2e/FintechConsentUiSmokeE2ETest.java
- fintech-examples/fintech-example-tests/src/test/java/de/adorsys/fintech/tests/e2e/config/FintechCookieProperties.java
- fintech-examples/fintech-example-tests/src/test/java/de/adorsys/fintech/tests/e2e/config/SmokeConfig.java
- fintech-examples/fintech-example-tests/src/test/java/de/adorsys/fintech/tests/e2e/steps/FintechServer.java
- fintech-examples/fintech-example-tests/src/test/java/de/adorsys/fintech/tests/e2e/steps/WebDriverBasedUserInfoFintech.java
- fintech-examples/fintech-example-tests/src/test/resources/application-test-mocked-fintech.yml
https://github.com/adorsys/open-banking-gateway/issues/856
> #856 Fix FintechConsentUiSmokeE2ETest class

- opba-protocols/protocol-bpmn-shared/src/main/java/de/adorsys/opba/protocol/bpmnshared/config/flowable/JsonCustomSerializer.java
- opba-protocols/protocol-bpmn-shared/src/test/java/de/adorsys/opba/protocol/bpmnshared/config/flowable/JsonCustomSerializerTest.java
- opba-protocols/protocol-bpmn-shared/src/test/java/de/adorsys/opba/protocol/bpmnshared/config/flowable/LargeJsonCustomSerializerTest.java
https://github.com/adorsys/open-banking-gateway/issues/930
> #930 JsonSerializer issue when serialized entity has 2048 byte size 

- fintech-examples/fintech-impl/src/main/java/de/adorsys/opba/fintech/impl/service/BankSearchService.java
- fintech-examples/fintech-impl/src/test/java/de/adorsys/opba/fintech/impl/service/BankSearchServiceTest.java
- opba-banking-rest-impl/src/test/java/de/adorsys/opba/tppbankingapi/controller/TestTppBankSearchController.java
- opba-banking-rest-impl/src/test/java/de/adorsys/opba/tppbankingapi/service/BankServiceTest.java
https://github.com/adorsys/open-banking-gateway/issues/797
> #797: FinTech server responds 500 on BankSearch when there are no matching results

- opba-consent-rest-api/src/main/resources/static/tpp_consent_api.yml
- opba-facade-protocol-api-shared/src/main/java/de/adorsys/opba/protocol/api/dto/request/authorization/AisAccountAccess.java
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/resources/restrecord/tpp-ui-input/params/anton-brueckner-account-wrong-ibans.json
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/resources/restrecord/tpp-ui-input/params/anton-brueckner-dedicated-account-consent.json
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/resources/restrecord/tpp-ui-input/params/anton-brueckner-transactions-single-account-consent.json
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/resources/restrecord/tpp-ui-input/params/max-musterman-dedicated-account-consent-wrong-iban.json
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/resources/restrecord/tpp-ui-input/params/max-musterman-transactions-single-account-consent.json
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/resources/restrecord/tpp-ui-input/params/new-user-transactions-single-account-consent.json
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/resources/restrecord/tpp-ui-input/params/unknown-user-transactions-single-account-consent.json
- opba-protocols/xs2a-protocol/src/main/java/de/adorsys/opba/protocol/xs2a/service/xs2a/dto/consent/AisConsentInitiateBody.java
https://github.com/adorsys/open-banking-gateway/issues/299
> #299 Add currency support to account reference (open api)

- opba-protocols/sandboxes/hbci-sandbox/src/main/java/de/adorsys/opba/protocol/sandbox/hbci/domain/HbciSandboxPayment.java
- opba-protocols/sandboxes/hbci-sandbox/src/main/java/de/adorsys/opba/protocol/sandbox/hbci/service/HbciSandboxPaymentService.java
- pom.xml
update lombok and mapstruct to work correctly with last intelliJ
https://github.com/rzwitserloot/lombok/issues/2592
> OBG-959 update multibanking to 5.5.24

- fintech-examples/fintech-impl/src/main/java/de/adorsys/opba/fintech/impl/service/BankSearchService.java
- fintech-examples/fintech-impl/src/test/java/de/adorsys/opba/fintech/impl/service/BankSearchServiceTest.java
- fintech-examples/fintech-server/src/test/java/de/adorsys/opba/fintech/server/FinTechBankSearchApiTest.java
- fintech-examples/fintech-server/src/test/java/de/adorsys/opba/fintech/server/FinTechListAccountsTest.java
- fintech-examples/fintech-server/src/test/java/de/adorsys/opba/fintech/server/feignmocks/TppBankSearchClientFeignMock.java
- firefly-exporter/src/main/java/de/adorsys/opba/fireflyexporter/controller/mvc/ViewController.java
- firefly-exporter/src/main/java/de/adorsys/opba/fireflyexporter/controller/rest/SearchController.java
- opba-admin-rest-api/src/main/resources/static/tpp_admin_api.yml
- opba-admin-rest-impl/src/main/java/de/adorsys/opba/adminapi/service/AdminApiService.java
- opba-banking-rest-api-ymls/src/main/resources/static/tpp_banking_api_bank_search.yml
- opba-banking-rest-impl/src/main/java/de/adorsys/opba/tppbankingapi/controller/TppBankSearchController.java
- opba-banking-rest-impl/src/main/java/de/adorsys/opba/tppbankingapi/service/BankService.java
- opba-banking-rest-impl/src/test/java/de/adorsys/opba/db/domain/MappersTest.java
- opba-banking-rest-impl/src/test/java/de/adorsys/opba/tppbankingapi/controller/TestTppBankSearchController.java
- opba-banking-rest-impl/src/test/java/de/adorsys/opba/tppbankingapi/service/BankServiceTest.java
- opba-banking-rest-impl/src/test/resources/application.yml
- opba-db/src/main/java/de/adorsys/opba/db/domain/entity/Bank.java
- opba-db/src/main/java/de/adorsys/opba/db/domain/entity/BankProfile.java
- opba-db/src/main/java/de/adorsys/opba/db/repository/BankSearchRepositoryImpl.java
- opba-db/src/main/resources/migration/master.xml
- opba-db/src/main/resources/migration/migrations/0012-add-is-active-field-to-bank.xml
- opba-embedded-starter/src/main/resources/application.yml
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/resources/application-test-one-time-postgres-ramfs.yml
Add isActive field to Bank search API, bank and bankProfiles models,
possibility to get only active data or all data, 
add migration.
> Add query parameter to bankSearch endpoints,

- fintech-examples/fintech-impl/src/main/java/de/adorsys/opba/fintech/impl/service/AccountService.java
- fintech-examples/fintech-impl/src/main/java/de/adorsys/opba/fintech/impl/service/PaymentService.java
- fintech-examples/fintech-impl/src/main/java/de/adorsys/opba/fintech/impl/service/TransactionService.java
- fintech-examples/fintech-impl/src/main/java/de/adorsys/opba/fintech/impl/tppclients/Consts.java
- fintech-examples/fintech-server/src/test/java/de/adorsys/opba/fintech/server/FinTechListAccountsTest.java
- fintech-examples/fintech-server/src/test/java/de/adorsys/opba/fintech/server/FinTechListTransactionsTest.java
- fintech-examples/fintech-server/src/test/java/de/adorsys/opba/fintech/server/feignmocks/TppAisClientFeignMock.java
- firefly-exporter/src/main/java/de/adorsys/opba/fireflyexporter/service/AccountExportService.java
- firefly-exporter/src/main/java/de/adorsys/opba/fireflyexporter/service/ConsentService.java
- firefly-exporter/src/main/java/de/adorsys/opba/fireflyexporter/service/ExportableAccountService.java
- firefly-exporter/src/main/java/de/adorsys/opba/fireflyexporter/service/FireFlyTransactionExporter.java
- opba-banking-rest-api-ymls/src/main/resources/static/tpp_banking_api_ais.yml
- opba-banking-rest-api-ymls/src/main/resources/static/tpp_banking_api_commons.yml
- opba-banking-rest-api-ymls/src/main/resources/static/tpp_banking_api_pis.yml
- opba-banking-rest-impl/src/main/java/de/adorsys/opba/tppbankingapi/controller/TppBankingApiAisController.java
- opba-banking-rest-impl/src/main/java/de/adorsys/opba/tppbankingapi/controller/TppBankingApiPisController.java
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/java/de/adorsys/opba/protocol/xs2a/tests/e2e/stages/StagesCommonUtil.java
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-wiremock/src/main/java/de/adorsys/opba/protocol/xs2a/tests/e2e/wiremock/mocks/WiremockAccountInformationRequest.java
Add headers to api. Fix controllers, tests.
> OBG-95 Document the usage of PSU-IP-Address and Compute-PSU-IP-Address headers

- fintech-examples/fintech-db-schema/src/main/resources/migration/migrations/0000-init-schema.xml
- fintech-examples/fintech-impl/src/main/java/de/adorsys/opba/fintech/impl/database/entities/PaymentEntity.java
- fintech-examples/fintech-impl/src/main/java/de/adorsys/opba/fintech/impl/service/HandleAcceptedService.java
- fintech-examples/fintech-impl/src/main/java/de/adorsys/opba/fintech/impl/service/PaymentService.java
- opba-banking-rest-api-ymls/src/main/resources/static/tpp_banking_api_pis.yml
- opba-facade-protocol-api-shared/src/main/java/de/adorsys/opba/protocol/api/dto/request/payments/SinglePaymentBody.java
- opba-facade-protocol-api-shared/src/main/java/de/adorsys/opba/protocol/api/dto/result/body/PaymentProductDetails.java
- opba-protocols/hbci-protocol/src/main/java/de/adorsys/opba/protocol/hbci/entrypoint/pis/HbciInitiateSinglePaymentEntrypoint.java
- opba-protocols/xs2a-protocol/src/main/java/de/adorsys/opba/protocol/xs2a/entrypoint/pis/Xs2aInitiateSinglePaymentEntrypoint.java
Add PaymentProduct to PaymentEntity in Fintech example.
> Add support of instant instant-sepa-payments for xs2a in OBG.

- consent-ui/src/app/ais/common/constant/constant.ts
- consent-ui/src/app/ais/entry-page/initiation/common/accounts-reference/accounts-reference.component.html
- consent-ui/src/app/ais/entry-page/initiation/common/accounts-reference/accounts-reference.component.spec.ts
- consent-ui/src/app/ais/entry-page/initiation/common/accounts-reference/accounts-reference.component.ts
- consent-ui/src/styles.scss
- opba-embedded-starter-tests/src/test/java/de/adorsys/opba/starter/FintechPasswordApplyTest.java
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-sandbox/src/main/java/de/adorsys/opba/protocol/xs2a/tests/e2e/sandbox/servers/WebDriverBasedAccountInformation.java
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/java/de/adorsys/opba/protocol/xs2a/tests/e2e/stages/AccountInformationRequestCommon.java
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/java/de/adorsys/opba/protocol/xs2a/tests/e2e/stages/AccountInformationResult.java
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/resources/restrecord/tpp-ui-input/params/new-user-deposit-account-custom-currency.json
- opba-protocols/xs2a-protocol-tests/xs2a-bdd-tests-common/src/main/resources/restrecord/tpp-ui-input/params/new-user-new-account-with-custom-currency-registration.json
- smoke-tests/src/test/java/de/adorsys/opba/smoketests/OpbaApiWithXs2aConsentUiSmokeE2ETest.java
- smoke-tests/src/test/java/de/adorsys/opba/smoketests/steps/SmokeSandboxServers.java
Fixed bug in consentUI when creating dedicated consent with several accounts (displaying an incorrect list of accounts)
> Added selection of currency for account to consentUI (dedicated consent flow)
